### ISSUE TITLE
Fix bpf program logging 

### ISSUE THREAD

**Issue by astoycos** [Kong/blixt#63]
When running blixt in kind I noticed the bpf program logging (facilitated by [aya-log](https://github.com/aya-rs/aya/tree/main/aya-log)) wasn't working. 

Specifically in one of the dataplane pods I see the following crash 

```
[astoycos@localhost integration]$ kubectl logs blixt-dataplane-4j5nc -n blixt-system
[2023-01-09T17:35:51Z INFO  loader] loading ebpf programs
[2023-01-09T17:35:51Z INFO  loader] attaching tc_ingress program to eth0
[2023-01-09T17:35:51Z INFO  loader] attaching tc_egress program to eth0
[2023-01-09T17:35:51Z INFO  loader] starting api server
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/aya-log-0.1.11/src/lib.rs:110:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/aya-log-0.1.11/src/lib.rs:110:45
```
We will need to dig into aya-log to figure out what's causing this failure.

**Comment by astoycos** [comment]
This ended up being fixed for me by regenerating my local `Cargo.Lock` file with `cargo lockfile-generate` which automatically bumped our aya-log 

`aya-log = "0.1"` (in our tracked Cargo.toml) 

from "0.1.11" to "0.1.13"
